[package]
name = "acorn-trunk-rdbms"
version = "0.0.1-alpha.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
acorn-core = { path = "../acorn-core" }
tracing = { workspace = true }

[features]
default = ["sqlite"]
sqlite = []
postgres = []
mysql = []
sqlserver = []
